#!/usr/bin/env bash

APP_NAME=lura
APP_PORT=80

CI_COMMIT_SHA=$(git log -n 1 --pretty=format:'%h')

DOCKER_REGISTRY_SERVER=registry.cn-chengdu.aliyuncs.com/lura
DOCKER_IMAGE=${DOCKER_REGISTRY_SERVER}/${APP_NAME}:build-${CI_COMMIT_SHA}

upload() {
  username=$1
  password=$2
  ENV=${3:-sit}
   echo "${password}" |sudo docker login --username="${username}"  registry.cn-chengdu.aliyuncs.com --password-stdin
   sudo docker build  -f deploy/Dockerfile -t ${DOCKER_IMAGE} .
   sudo docker push ${DOCKER_IMAGE}
   sudo docker rmi ${DOCKER_IMAGE}
}

deploy() {
  ENV=${1:-sit}
  NAMESPACE=${1:-default}
  URL="$APP_NAME.$ENV.yumimiao.cn"

    kubeCmd='sudo kubectl'

  $kubeCmd create namespace "$NAMESPACE" || true
  cat deploy/deployment.yml | \
        sed "s#\$ENV#$ENV#g" | \
        sed "s#\$URL#$URL#g" | \
        sed "s#\$NAMESPACE#$NAMESPACE#g" | \
        sed "s#\$APP_NAME#$APP_NAME#g" | \
        sed "s#\$APP_PORT#$APP_PORT#g" | \
        sed "s#\$DOCKER_IMAGE#$DOCKER_IMAGE#g" | \
        $kubeCmd apply -f -
}

case $1 in
 upload )
   $1 $2 $3 $4;;
 deploy )
   $1 $2 $3;;
 * )
   echo "not support!!! example: ./ci <upload|deploy>"
   exit 1;;
esac
